[profile.default]
  auto_detect_solc = false
  bytecode_hash = "none"
  evm_version = "shanghai"
  fuzz = { runs = 1_000 }
  gas_reports = ["*"]
  optimizer = true
  optimizer_runs = 10_000
  out = "out"
  script = "script"
  solc = "0.8.24"
  src = "src"
  test = "test"
  libs = ["node_modules"]

# above are yoinked from PRB foundry template
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
